name: Run all tests
on: [push]

jobs:
  build:
    runs-on: {{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Tests
      run: |
        python run_tests.py
